In [3]:
import pandas as pd

In [4]:
# Criar um dataframe Pandas a partir dos dados da amostra do Orange
dados = pd.read_csv('/content/SAMPLE_ENERGY_DATA.csv')

# **ANÁLISE EXPLORATÓRIA PRELIMINAR**

In [5]:
# Visualizar registros iniciais
dados.head()

,Date,Time,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3
0,2008-12-01 00:00:00,2026-08-03 09:44:00,1.502,0.074,240.17,6.4,0,0,18
1,2006-12-17 00:00:00,2026-08-03 23:39:00,0.374,0.264,245.50,1.8,0,2,0
2,2009-06-03 00:00:00,2026-08-03 17:01:00,0.620,0.300,239.85,3.0,0,1,1
3,2007-05-09 00:00:00,2026-08-03 05:53:00,0.280,0.200,235.72,1.4,0,0,0
4,2008-12-14 00:00:00,2026-08-03 02:57:00,1.372,0.054,243.95,5.6,0,0,18

In [6]:
# Dimensões do dataframe
dados.shape

(40986, 9)

In [7]:
# Informações dos atributos
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40986 entries, 0 to 40985
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Date                   40986 non-null  object
 1   Time                   40986 non-null  object
 2   Global_active_power    40986 non-null  float64
 3   Global_reactive_power  40986 non-null  float64
 4   Voltage                40986 non-null  float64
 5   Global_intensity       40986 non-null  float64
 6   Sub_metering_1         40986 non-null  int64
 7   Sub_metering_2         40986 non-null  int64
 8   Sub_metering_3         40986 non-null  int64
dtypes: float64(4), int64(3), object(2)
memory usage: 2.8+ MB

In [8]:
# Estatísticas descritivas dos atributos numéricos
# contagem, min, max, média, mediana, desvio padrão, distribuição dos quartis
dados.describe()

,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3
count,40986.000000,40986.000000,40986.000000,40986.000000,40986.000000,40986.000000,40986.000000
mean,1.098045,0.125255,240.843132,4.653838,1.166984,1.280120,6.532816
std,1.059122,0.112929,3.242971,4.448916,6.276977,5.751622,8.474909
min,0.076000,0.000000,225.900000,0.200000,0.000000,0.000000,0.000000
25%,0.310000,0.050000,239.000000,1.400000,0.000000,0.000000,0.000000
50%,0.613000,0.102000,241.020000,2.600000,0.000000,0.000000,1.000000
75%,1.536000,0.196000,242.870000,6.400000,0.000000,1.000000,17.000000
max,10.290000,1.000000,253.320000,44.600000,80.000000,77.000000,31.000000